### ISSUE TITLE
README example has sudo

### ISSUE THREAD

**Issue by AkihiroSuda** [majek/slirpnetstack#1]
https://github.com/majek/slirpnetstack#usage-with-custom-network-namespace

As in slirp4netns, sudo shouldn't be required?

**Comment by AkihiroSuda** [comment]
Doesn't work without sudo? :cry:

```console
$ nsenter -U -t 15375 --preserve-credentials slirpnetstack -interface tun0 -netns /proc/15375/ns/net
[.] Joininig netns /proc/15375/ns/net
[.] Opening tun interface tun0
[.] Restoring root netns
panic: error restoring namespace: of type network: operation not permitted

goroutine 1 [running, locked to thread]:
gvisor.dev/gvisor/runsc/specutils.ApplyNS.func1()
        /home/suda/gopath/pkg/mod/gvisor.dev/gvisor@v0.0.0-20200109212014-516bba9edc31/runsc/specutils/namespace.go:146 +0x2d8
main.joinNetNS.func1()
        /home/suda/gopath/src/github.com/majek/slirpnetstack/netns_utils.go:22 +0x24
main.GetTunTap(0x7ffd434f74e4, 0x12, 0x7ffd434f74d8, 0x4, 0x2, 0xc000024790, 0x0, 0x2)
        /home/suda/gopath/src/github.com/majek/slirpnetstack/stack.go:62 +0x307
main.Main(0xc00007a058)
        /home/suda/gopath/src/github.com/majek/slirpnetstack/main.go:125 +0x87b
main.main()
        /home/suda/gopath/src/github.com/majek/slirpnetstack/main.go:39 +0x22
```

**Comment by majek** [comment]
This is kinda your job :)

So, if you run the whole thing in "unshare -Ur" then fine, you don't need sudo - since you will have permissions to enter your-created netns.

In standard linux though, you don't have permissions to enter arbitrary network namespace, even if it's you that created it. Or am I getting something wrong? How to enter /proc/<pid>/ns/net without either Unshare -Ur or root?

**Comment by AkihiroSuda** [comment]
> So, if you run the whole thing in "unshare -Ur" then fine,

Didn't work for me (Ubuntu 19.10, kernel `5.3.0-26-generic #28-Ubuntu`)

**Comment by majek** [comment]
ok, I see it. let me figure out what is wrong

**Comment by majek** [comment]
@AkihiroSuda try now please
