### ISSUE TITLE
IPv6 Address Space

### ISSUE THREAD

**Issue by joel0** [majek/slirpnetstack#19]
The IPv6 container addresses are `2001:2::2` and `2001:2:100` with a /32 network mask.  Is there any specific reason for using this network?

[RFC 5180](https://www.rfc-editor.org/rfc/rfc5180.txt), [errata 1752](https://www.rfc-editor.org/errata_search.php?eid=1752) reserves those specific addresses for benchmarking and the network for "for testing and experimental usage".  I think a network within `fd00::/8` would be more aligned with [RFC 4193](https://tools.ietf.org/html/rfc4193).

**Comment by majek** [comment]
Interesting take.

So `fd00::` is a subnet of `f700::` from https://tools.ietf.org/html/rfc4193.  Wikipedia is better https://en.wikipedia.org/wiki/Unique_local_address

Can we set "prefix" to be 0 or is it too much?

In any case, we should do fdxx..../64 .... Ok, let's try.
